return {
	"Ardornis Version: 3.2";
	"Run ;changelog to see Adonis changes!";
	"*Drag edges to expand*";
	"";
	"Ardornis 3.2";
	"- Changed many player-facing mentions of Adonis to Ardornis where a player can see it";
	"	- Includes: commands, F9/studio output, etc";
	"- Backend scripts also say Ardornis where it doesn't break the script";
	"	- issues might arise from this";
	"- Changelogs and Ardornis changelogs separated into ;changelogs for Adonis, ;ardornischangelog for Ardornis";
	"	- This is to reduce merge conflicts by utilizing modularity";
	"";
	"Ardornis 3.1b";
	"- Donating through Ardornis is disabled";
	"- Donator commands disabled";
	"- Output recolored";
	"";
	"Ardornis 3.1a";
	"- Necessary changes as required by Roblox";
	"- Output's transparency tweaked";
	"- Notifications are no longer blank";
	"";
	"Ardornis 3.1";
	"- adonis update: Rebased to Adonis v239a: About 7 months of changes caught up on";
	"- Redesigned UI again";
	"	- Sounds added to messages, notifications, small messages, and outputs (errors)";
	"";
	"Ardornis 3.0";
	"- Initial release: rebased to Adonis v238, Sep 26 2022";
}
